<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Home Page Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used during authentication for various
    | messages that we need to display to the user. You are free to modify
    | these language lines according to your application's requirements.
    |
    */

    '1t' => '¿Qué es el Café Especial?',
    '2t' => 'Conoce Tu Cacao Con Uncommon Cacao',
    '3t' => 'La Fermentación del Café y Sus Procesos',
    '4t' => 'Explorando el Café de Especialidad',
    '5t' => 'Ecotact Lanza Una Iniciativa de Reciclaje y Sostenibilidad',
    '6t' => 'Procesamiento de Miel y Procesamiento Natural Del Café Verde con Ecotact',
    '7t' => 'Explorando Las Facetas de La Producción de Café Con el Señor Carlos Melen- Director General de Good Coffee Farms',
    '8t' => 'Conversaciones en Torno A UN Café Con Hendra Taruli, Directora de Opal Coffee',
    '9t' => 'Preguntas y Respuestas Con Kyle Bellinger',
    '10t' => 'Opiniones de Samuel Coto Sobre el Sector',
    '11t' => 'Palabras de La Primera Dama Del Café de Asia',
    '12t' => '5 Formas A Través de Las Cuales Los Envases de 9 Capas Mantienen Intacta La Calidad de Los Granos Alimenticios',
    '13t' => 'Ecotact Presenta Las Nuevas Bolsas De Embalaje Herméticas Ecológicas, Especialmente Diseñadas Con Triple Protección Para Pequeños Tostadores, Tostadores Doméstico Y Baristas.',
    
    
    '1' => '<p><span style="font-weight: 400;">El caf&eacute; de especialidad est&aacute; de moda desde hace tiempo. Pero, &iquest;qu&eacute; es exactamente lo que convierte al caf&eacute; en una especialidad? Exploremos primero los matices de un caf&eacute; de especialidad. El t&eacute;rmino "especial" (que a menudo se confunde con especialidad, que se traduce como fortaleza) fue utilizado por primera vez para referirse al caf&eacute; en 1974 por Erna Knutsen en un n&uacute;mero de la revista Tea &amp; Coffee Journal. La palabra se utilizaba para describir el caf&eacute; que se produc&iacute;a en un microclima con perfiles de sabor &uacute;nicos y de alta calidad. Hoy, sin embargo, la palabra "especialidad " est&aacute; en todas partes en la industria. Se utiliza sin cesar en los envases y la se&ntilde;alizaci&oacute;n, y la emplean tanto los baristas como los tostadores. Pero con el tiempo, el significado y la esencia del caf&eacute; especialidad ha cambiado.</span></p>
    <p><span style="font-weight: 400;">Actualmente, en la producci&oacute;n de caf&eacute; el t&eacute;rmino "regular" se utiliza a menudo como sin&oacute;nimo de mala calidad, falta de sostenibilidad y transparencia. A su vez, esto significa que el caf&eacute; regular puede venir acompa&ntilde;ado de una experiencia desagradable por su mal sabor y una sensaci&oacute;n no muy agradable para tus sentidos. Por el contrario, en la mayor&iacute;a de los casos el caf&eacute; de especialidad significa calidad garantizada en todas las etapas de la producci&oacute;n del caf&eacute;, desde la semilla hasta su taza.</span></p>
    <p><span style="font-weight: 400;">Para entender la elaboraci&oacute;n del caf&eacute; de especialidad, entendamos primero el sistema de clasificaci&oacute;n. Todos los granos de caf&eacute; se clasifican sobre 100 seg&uacute;n el proceso de "cata". De acuerdo a la Asociaci&oacute;n de Caf&eacute;s Especiales (SCA), el caf&eacute; especial es un caf&eacute; ar&aacute;bigo con una puntuaci&oacute;n en taza superior a 80 puntos. Pero el caf&eacute; debe haber sido catado por un catador Q certificado. Adem&aacute;s, si se encuentra demasiados defectos en una muestra de caf&eacute; verdes y sin tostar, descalifica autom&aacute;ticamente ese caf&eacute; de la categor&iacute;a de especialidad.</span></p>
    <p><span style="font-weight: 400;">Pero, &iquest;el caf&eacute; de especialidad se refiere s&oacute;lo a los granos?</span></p>
    <p><span style="font-weight: 400;">Dado que los granos no pueden tener muchos defectos, las plantas de caf&eacute; deben ser cultivadas cuidadosamente y cosechadas en el momento adecuado. Los caf&eacute;s especiales son cultivados por los agricultores en altitudes y climas selectos y se cultivan durante a&ntilde;os, antes de la primera cosecha. En el procesamiento, se prioriza la calidad y no la cantidad. Posteriormente, el caf&eacute; se transfiere al comprador de caf&eacute; verde. Este identifica la calidad del caf&eacute; mediante la cata, o degustaci&oacute;n sistem&aacute;tica de caf&eacute;s tostados. A trav&eacute;s de la cata, el catador de caf&eacute; puede evaluar la puntuaci&oacute;n de un caf&eacute; y determinar si es de calidad especial o no. A continuaci&oacute;n, los caf&eacute;s de alta calidad se transfieren al tostador. El caf&eacute; debe ser supervisado estrechamente durante el proceso de tostado y deben aplicarse los principios cient&iacute;ficos de transferencia de calor, termodin&aacute;mica y qu&iacute;mica del caf&eacute;, a fin de garantizar finalmente el m&aacute;ximo nivel de calidad y sabor en el grano tostado. Luego, el caf&eacute; pasa a las manos del barista, quien debe asegurar que cada grano tostado alcance su m&aacute;ximo potencial.</span></p>
    <p><span style="font-weight: 400;">Evoluci&oacute;n de los caf&eacute;s de especialidad</span></p>
    <p><span style="font-weight: 400;">Sin embargo, a pesar de que tanto la escala de cata de la SCA como el sistema de clasificaci&oacute;n f&iacute;sica proporcionan definiciones objetivas, la definici&oacute;n de lo que es el caf&eacute; especial o, mejor dicho, lo que representa, parece haber cambiado.</span></p>
    <p><span style="font-weight: 400;">Hoy en d&iacute;a, la palabra "especialidad" se utiliza a menudo como sin&oacute;nimo de palabras como "artesanal", y se asocia con frecuencia a conceptos como transparencia, trazabilidad y comercio directo. Tambi&eacute;n se utiliza indistintamente por algunas personas con el concepto de caf&eacute; de tercera ola, que, a diferencia de la especialidad, no tiene una definici&oacute;n objetiva. Hoy en d&iacute;a, el caf&eacute; de especialidad ha evolucionado desde una definici&oacute;n objetiva hasta abarcar un ideal que atiende a una "comunidad de caf&eacute;s de especialidad".</span></p>
    <p><span style="font-weight: 400;">Mejores pr&aacute;cticas</span></p>
    <p><span style="font-weight: 400;">Los productores deben incorporar mejores pr&aacute;cticas de procesamiento, y tambi&eacute;n deben seguir los protocolos de almacenamiento. Por ello, se recomienda almacenar el caf&eacute; en envases herm&eacute;ticos de 9 capas, debido a que mejora el sabor y mantiene intacta la calidad. Ecotact se especializa en el desarrollo y venta de empaques herm&eacute;ticos multicapas, bolsas de alta calidad dise&ntilde;adas para el envasado de caf&eacute;s especiales.</span></p>
    <p><span style="font-weight: 400;">- Protege el aroma, la humedad y la actividad del agua del caf&eacute; especial</span></p>
    <p><span style="font-weight: 400;">- Proporciona una excelente visibilidad del grano y est&aacute;n certificados como empaques de grado alimenticio</span></p>
    <p><span style="font-weight: 400;">- Prolonga la vida &uacute;til y mantiene el caf&eacute; fresco durante mucho tiempo</span></p>
    <p><span style="font-weight: 400;">- No requiere el uso de insecticidas o pesticidas para su conservaci&oacute;n</span></p>
    <p><span style="font-weight: 400;">- Tolerancia a las altas temperaturas</span></p>
    <p><span style="font-weight: 400;">- Alta resistencia al aceite y a los disolventes</span></p>
    <p><span style="font-weight: 400;">- F&aacute;cil de reciclar y estructura ecoamigable</span></p>
        ',
    '2' => '<p><span style="font-weight: 400;">En conversaci&oacute;n con un miembro de Uncommon Cacao - Stasi Baranoff, sobre la industria del cacao.</span></p>
    <ul>
    <li aria-level="1"><strong>Cu&eacute;ntenos m&aacute;s sobre c&oacute;mo se aventur&oacute; en la industria del cacao.</strong></li>
    </ul>
    <p><span style="font-weight: 400;">En 2010, nuestra fundadora &amp; CEO- Emily Stone, sigui&oacute; su amor por el chocolate y su experiencia en el activismo medioambiental para crear una empresa de procesamiento de cacao en el sur de Belice. Ese fue el comienzo del Grupo Uncommon Cacao, una empresa social con certificaci&oacute;n B Corp dedicada a mejorar los medios de vida de los agricultores a trav&eacute;s de cadenas de suministro de cacao transparentes y de alta calidad. Somos un grupo de tres empresas: Maya Mountain Cacao (un procesador y exportador en Belice), Cacao Verapaz (un exportador en Guatemala) y Uncommon Cacao (un intermediario en Estados Unidos). Uncommon Cacao es un intermediario que vende granos de nuestras dos empresas hermanas, as&iacute; como de otros 8 socios proveedores en otros 8 pa&iacute;ses.&nbsp;</span></p>
    <p>&nbsp;</p>
    <p><strong>2) &iquest;C&oacute;mo ha evolucionado la industria del cacao en los &uacute;ltimos a&ntilde;os?</strong></p>
    <p><span style="font-weight: 400;">Desde que empezamos en el 2010, hemos observado un aumento del inter&eacute;s por las empresas de chocolate especializadas que se centran en ingredientes de alta calidad y de origen &eacute;tico. Nuestros clientes chocolateros, y sus clientes consumidores, esperan una consistencia en el producto con una historia impactante, ya sea un impacto social, medioambiental o econ&oacute;mico. En el pasado, los consumidores y los comerciantes consideraban el cacao y el chocolate como una mercanc&iacute;a fungible y barata. Hoy en d&iacute;a, la gente del sector entiende que las distintas calidades de cacao merecen precios diferentes y que los chocolateros y los consumidores no deber&iacute;an pensar en el cacao como una mercanc&iacute;a en absoluto.</span></p>
    <p>&nbsp;</p>
    <p><strong>3) &iquest;Cu&aacute;les son las mejores pr&aacute;cticas para producir un cacao de calidad?</strong></p>
    <p><span style="font-weight: 400;">La consistencia es la clave. Los chocolateros buscan la consistencia, con la misma calidad y sabor de una cosecha a otra. Para conseguirlo, los grupos de productores, o las empresas de transformaci&oacute;n, deben seguir protocolos de procesamiento para fermentar y secar los granos de cacao. El proceso habitual incluye estos pasos:</span></p>
    <p><span style="font-weight: 400;"><br /><br /></span></p>
    <ol>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Buenas pr&aacute;cticas agron&oacute;micas para mantener la salud de los &aacute;rboles y las mazorcas, para maximizar el rendimiento y asegurar la madurez de las mazorcas.</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Cosechar s&oacute;lo las mazorcas de cacao maduras, que tengan un grado BRIX (az&uacute;cares) lo suficientemente alto como para poder fermentar</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Colectar un volumen suficiente de pulpa de cacao y colocarlos en los cajones de fermentaci&oacute;n, para que los altos niveles de az&uacute;cares y &aacute;cidos que contiene la pulpa creen las condiciones ideales para tener &eacute;xito en el proceso de fermentaci&oacute;n.</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Llevar a cabo una fermentaci&oacute;n tanto anaer&oacute;bica como aer&oacute;bica, durante un lapso de 4 a 8 d&iacute;as, dependiendo de la ubicaci&oacute;n, el tipo de cacao y el volumen de cacao a fermentar.</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Realizar el proceso de secado en dos etapas; un proceso de secado lento, normalmente cubierto y sobre mesas de malla, y un secado r&aacute;pido al sol, en un patio, rastrillando frecuentemente durante todo el proceso</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Clasificar el cacao a mano si es posible, para garantizar que s&oacute;lo los granos de cacao enteros se introduzcan en los sacos para la exportaci&oacute;n.</span></li>
    </ol>
    <p>&nbsp;</p>
    <p><strong>4) &iquest;Qu&eacute; hace que las distintas variedades de cacao sean &uacute;nicas entre s&iacute;?</strong></p>
    <p><span style="font-weight: 400;">No hay cientos, sino miles de variedades de cacao, debido a la facilidad con la que se puede cruzar el cacao. Sin embargo, en t&eacute;rminos generales se considera que hay cuatro grupos familiares: Criollo, Amelonado, Forastero y Trinitario. Estas variedades se diferencian no s&oacute;lo por su forma y sus regiones de cultivo, sino tambi&eacute;n por sus notas de sabor generales.</span></p>
    <p>&nbsp;</p>
    <p><strong>5) &iquest;C&oacute;mo conserva sus productos de cacao? &iquest;Qu&eacute; importancia tienen las buenas soluciones de envasado herm&eacute;tico para su negocio y hay alguna marca espec&iacute;fica que prefiera?</strong></p>
    <p><span style="font-weight: 400;">El cacao se almacena generalmente en grandes sacos de polipropileno o yute/sisal. Estos sacos se almacenan en palets dentro de los almacenes. Dado que el cacao es sensible a los olores y se seca intencionadamente a un nivel de humedad muy espec&iacute;fico, el envasado herm&eacute;tico es esencial para obtener un producto de alta calidad. Nuestra empresa utiliza Ecotact, porque sirve para preservar la humedad y proteger del olor.</span></p>
    <p>&nbsp;</p>
    <p><strong>6) &iquest;Ha notado un cambio en el patr&oacute;n de consumo/demanda de cacao durante la pandemia?</strong></p>
    <p><span style="font-weight: 400;">El cacao de especialidad o fino de sabor, ha mantenido sus patrones de consumo, y el chocolate artesanal ha resistido en su mayor parte. Hemos observado una reducci&oacute;n de la demanda de cacao en grano durante los meses de verano, pero con el comienzo de la temporada de vacaciones, la demanda est&aacute; volviendo a aumentar a medida que nuestros clientes elaboran chocolate para las fiestas de la temporada de vacaciones.</span></p>
    <p>&nbsp;</p>
    <p><strong>7) &iquest;C&oacute;mo cree que los envases herm&eacute;ticos est&aacute;n ayudando a la industria del cacao en estos tiempos dif&iacute;ciles?</strong></p>
    <p><span style="font-weight: 400;">Un almacenamiento confiable y limpio es esencial en esta &eacute;poca. Al disminuir las compras, el cacao necesita mantener su humedad y calidad. Como empresa, decidimos seguir operando y mantener nuestros compromisos de compra originales con cada uno de nuestros proveedores de cacao. Sab&iacute;amos que el cacao es m&aacute;s estable en su estado fermentado y seco, y se conserva mejor envasado en bolsas herm&eacute;ticas. Si un agricultor dejara que el fruto se pudriera en el &aacute;rbol, inevitablemente sus futuras cosechas se ver&iacute;an afectadas por las enfermedades que pueden propagarse f&aacute;cilmente cuando los &aacute;rboles no se mantienen. Sab&iacute;amos que, si los ingresos segu&iacute;an llegando a los agricultores, las parcelas se mantendr&iacute;an y ser&iacute;an m&aacute;s resistentes a las enfermedades para futuras cosechas. En consecuencia, nos aseguramos de cumplir nuestros compromisos, y con el cacao empacado en bolsas Ecotact en un almac&eacute;n estadounidense, sabemos que podemos mantener este cacao en buena calidad durante meses y potencialmente a&ntilde;os.</span></p>
    <p>&nbsp;</p>
    <p><strong>8) &iquest;Ha afectado la pandemia negativamente a la industria del cacao?</strong></p>
    <p><span style="font-weight: 400;">Parece haber afectado de forma diferente a las distintas regiones productoras y consumidoras de cacao, por lo que es dif&iacute;cil afirmar de forma general que ha afectado negativamente a toda la industria. Por suerte, en su mayor parte, las regiones productoras de cacao parecen estar levemente afectadas por la pandemia en t&eacute;rminos de salud en las regiones. Las comunidades agr&iacute;colas rurales est&aacute;n m&aacute;s repartidas, por lo que el COVID no parece extenderse tanto. Esto significa que los agricultores est&aacute;n sanos y son capaces de atender sus fincas.</span></p>
    <p>&nbsp;</p>
    <p><strong>9) &iquest;Qu&eacute; Niveles de humedad prefiere para envasar el cacao en bolsas Ecotact?</strong></p>
    <p><span style="font-weight: 400;">El cacao debe tener un nivel de humedad inferior al 7,5%, idealmente entre el 6 y el 7,5%. Esto es para evitar el crecimiento de moho tanto en el exterior como en el interior de los granos. Por lo tanto, nuestros proveedores envasan su cacao en bolsas herm&eacute;ticas con un nivel de humedad en este rango, para mantener su estabilidad y sabor.</span></p>
    <p>&nbsp;</p>
    <p><strong>10) &iquest;Utilizan las bolsas Ecotact tambi&eacute;n para el almacenamiento en el almac&eacute;n o s&oacute;lo para la exportaci&oacute;n?</strong></p>
    <p><span style="font-weight: 400;">Mantenemos el cacao almacenado en bolsas Ecotact tanto en el pa&iacute;s de origen como en los almacenes de Estados Unidos. Tanto en los almacenes de origen como en los de destino, el cacao puede entrar en contacto con una serie de riesgos: olores, climas h&uacute;medos, polillas del cacao, por lo que intentamos hacer todo lo posible para preservar la calidad. Esto incluye mantener el cacao almacenado en bolsas Ecotact.</span></p>
        ',
    '3' => '<p><strong>&iquest;Tiene curiosidad por conocer la fermentaci&oacute;n del caf&eacute; y lo que diferencia al caf&eacute; cultivado del resto?</strong><span style="font-weight: 400;">&nbsp;</span></p>
    <p>&nbsp;</p>
    <p><span style="font-weight: 400;">Es hora de saciar su curiosidad. Entendamos primero los fundamentos de la fermentaci&oacute;n.</span></p>
    <p>&nbsp;</p>
    <p><span style="font-weight: 400;">La fermentaci&oacute;n es una reacci&oacute;n qu&iacute;mica. La combinaci&oacute;n de levaduras, bacterias y otros microorganismos hace que una sustancia se descomponga en otras m&aacute;s simples. Normalmente, las sustancias que se descomponen son az&uacute;cares. Cuando esto ocurre, tienden a liberar calor. Adem&aacute;s, diferentes tipos de enzimas pueden catalizar este acontecimiento.</span></p>
    <p>&nbsp;</p>
    <p><span style="font-weight: 400;">O, para decirlo de forma m&aacute;s sencilla, la fermentaci&oacute;n es un cambio natural que se produce cuando se juntan el az&uacute;car y el agua, y las cerezas del caf&eacute; est&aacute;n llenas de ambos. Y as&iacute;, justo despu&eacute;s de recoger las cerezas (o a veces antes, seg&uacute;n la humedad), comenzar&aacute; el proceso de fermentaci&oacute;n.</span></p>
    <p>&nbsp;</p>
    <p><span style="font-weight: 400;">La fermentaci&oacute;n es una parte fundamental del procesamiento del caf&eacute; despu&eacute;s de la cosecha. Puede ocurrir de dos maneras:</span></p>
    <p>&nbsp;</p>
    <p><span style="font-weight: 400;">Aer&oacute;bica: es la que ocurre cuando hay ox&iacute;geno disponible. La ingenier&iacute;a de este tipo de fermentaci&oacute;n es sencilla. Para la producci&oacute;n de caf&eacute; lavado, el per&iacute;odo de tiempo en el que el caf&eacute; despulpado se macera generalmente en tanques de fermentaci&oacute;n al aire libre o ahora tambi&eacute;n en bolsas herm&eacute;ticas Ecotact aptas para alimentos, el proceso se conoce como fermentaci&oacute;n aer&oacute;bica. Es un m&eacute;todo tradicional de fermentaci&oacute;n y los agricultores lo utilizan para eliminar el muc&iacute;lago de la fruta de la semilla de caf&eacute; cubierta de pergamino. El cambio de sabor, aunque importante, es la mayor&iacute;a de las veces secundario a la eliminaci&oacute;n de los az&uacute;cares de la fruta y la pectina. El per&iacute;odo de tiempo asignado para la fermentaci&oacute;n aer&oacute;bica es de 12 a 24 horas. Si la temperatura es elevada, basta con fermentar durante 12 horas.</span></p>
    <p>&nbsp;</p>
    <p><span style="font-weight: 400;">Anaer&oacute;bico: en general, anaer&oacute;bico significa libre de ox&iacute;geno. Cuando los caficultores utilizan esta palabra, suelen significar que han creado un entorno sellado.</span></p>
    <p>&nbsp;</p>
    <p><span style="font-weight: 400;">Ahora entendamos el proceso de fermentaci&oacute;n en una bolsa Ecotact.</span></p>
    <p><span style="font-weight: 400;"><br /><br /></span></p>
    <ul>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Granos con mucílago se coloca en bolsas de pl&aacute;stico Ecotact herm&eacute;ticas con una v&aacute;lvula para permitir la desgasificaci&oacute;n.</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Coloque las bolsas Ecotact en agua fr&iacute;a para evitar las bacterias.</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">A medida que se inicia la fermentaci&oacute;n, los niveles de ox&iacute;geno disminuyen y el di&oacute;xido de carbono aumenta, lo que crea una presi&oacute;n en las resistentes bolsas Ecotact herm&eacute;ticas expandibles.</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Este estilo de fermentaci&oacute;n puede alargar el plazo tradicional de 12-24 horas en horas o incluso d&iacute;as en algunos casos y lo suficiente como para que se consuma el muc&iacute;lago, pero no tanto como para que se produzca alcohol.</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Despu&eacute;s de 12 horas es necesario comprobar o controlar constantemente el pH para determinar c&oacute;mo progresa la fermentaci&oacute;n. Medir los grados Brix del caf&eacute; de vez en cuando tambi&eacute;n puede ayudar.</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Normalmente, el proceso de fermentaci&oacute;n puede detenerse cuando los grados Brix bajan a 16 &deg;Bx. La presi&oacute;n creada por el di&oacute;xido de carbono permite que los sabores de los jugos del caf&eacute; se inyecten en el pergamino. Una vez concluida la fermentaci&oacute;n, los sacos Ecotact se abren con cuidado.</span></li>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">A continuaci&oacute;n, el caf&eacute; se seca al sol durante al menos 4 horas, ya que de lo contrario la fermentaci&oacute;n podr&iacute;a continuar y los sabores podr&iacute;an cambiar.</span></li>
    </ul>
    <p>&nbsp;</p>
    <p><span style="font-weight: 400;">Entonces, &iquest;cu&aacute;l es la diferencia? Los procesos anaer&oacute;bicos son m&aacute;s homog&eacute;neos y m&aacute;s f&aacute;ciles de controlar, y los aer&oacute;bicos son m&aacute;s heterog&eacute;neos y m&aacute;s complejos de controlar.</span></p>
    <p><span style="font-weight: 400;">Para evaluar el comportamiento de los granos en las condiciones ambientales dadas, tambi&eacute;n es necesario tomar en cuenta otras variables como: la temperatura, la variedad de caf&eacute;, la humedad, el pH, ver si la cosecha es homog&eacute;nea, etc.</span></p>
    <p><strong>Consideraciones a tener en cuenta</strong></p>
    <p><span style="font-weight: 400;">La fermentaci&oacute;n anaer&oacute;bica del caf&eacute; es s&oacute;lo una de las interesantes innovaciones que se producen en las fincas que cuentan con visi&oacute;n de futuro. Este tipo de pr&aacute;cticas progresistas y experimentales pueden fomentar la creatividad en un sector que suele depender de la tradici&oacute;n, y proporcionar una diferenciaci&oacute;n de mercado a los productores que buscan liberarse de los precios del mercado C.</span></p>
        ',
    '4' => '<p><span style="font-weight: 400;">En una emocionante conversaci&oacute;n con Arnaud Causse - CEO de Las Tolas Estate Coffee - Ecuador, exploramos la producci&oacute;n del caf&eacute; de especialidad y su popularidad.</span></p>
    <p><strong>1) Cu&eacute;ntenos m&aacute;s sobre c&oacute;mo se aventur&oacute; en la industria de los caf&eacute;s especiales.</strong></p>
    <p><span style="font-weight: 400;">&nbsp;Durante una larga misi&oacute;n en El Salvador, despu&eacute;s de los Acuerdos de Paz, descubr&iacute; que ciertos caf&eacute;s pod&iacute;an ser valorados en nichos de mercado que comenzaban a diferenciarse.</span></p>
    <p><span style="font-weight: 400;">Mientras buscaba mejorar la calidad y la fama del caf&eacute; de Gal&aacute;pagos, decid&iacute; encontrar el lugar ideal para producir un caf&eacute; altamente diferenciado, bas&aacute;ndome en mis experiencias alrededor del mundo aplicando el principio de las "capas" en un mapa. As&iacute; naci&oacute; el proyecto Finca Las Tolas en el noroeste de Pichincha. La recepci&oacute;n apenas comenzamos la producci&oacute;n fue muy alentadora surfeando en la tercera ola en su inicio.</span></p>
    <p>&nbsp;</p>
    <p><strong>2) &iquest;Qu&eacute; le inspir&oacute; a experimentar con diferentes t&eacute;cnicas de cultivo de caf&eacute;? Por favor, comparta un poco sobre ellas. &iquest;C&oacute;mo distinguen estos procesos a su caf&eacute;?</strong></p>
    <p><span style="font-weight: 400;">La inspiraci&oacute;n proviene de la acumulaci&oacute;n de experiencias e intercambios con multitud de productores apasionados de &Aacute;frica, Centroam&eacute;rica, el Caribe y Sudam&eacute;rica. A esto se suma la observaci&oacute;n permanente del comportamiento de los cafetales de Las Tolas y Terrazas del Pisque y los resultados de las catas.</span></p>
    <p><span style="font-weight: 400;">El manejo agroecol&oacute;gico que implementamos est&aacute; dando resultados sorprendentes tanto en la productividad como en la generaci&oacute;n de precursores del aroma. Con estas t&eacute;cnicas podemos garantizar una &oacute;ptima calidad intr&iacute;nseca de nuestro(s) caf&eacute;(s) que sublimamos y luego atomizamos a trav&eacute;s de diversos procesos de post-cosecha para constituir toda una amplia gama de caf&eacute;s con expresiones potenciales.</span></p>
    <p>&nbsp;</p>
    <p><strong>3) &iquest;C&oacute;mo ha ganado reconocimiento el caf&eacute; Sidra en los &uacute;ltimos a&ntilde;os y c&oacute;mo seguir&aacute; en los pr&oacute;ximos, seg&uacute;n usted?</strong></p>
    <p><span style="font-weight: 400;">El caf&eacute; Sidra ha ganado mucha fama por su excelente comportamiento en la taza; sin embargo, su "huella" gen&eacute;tica a&uacute;n no est&aacute; definida y por lo tanto la variaci&oacute;n es incontrolable. Creo que la &uacute;nica conclusi&oacute;n sostenible es que el cruce entre Bourbones y ciertas reliquias procedentes del germoplasma et&iacute;ope permite el desarrollo de poblaciones muy prometedoras en ciertas condiciones particulares.</span></p>
    <p><span style="font-weight: 400;">La sidra, como la Geisha, tendr&aacute; sus a&ntilde;os de gloria hasta que aparezca una nueva familia de cultivares con caracter&iacute;sticas m&aacute;s adaptadas a las expectativas del mercado o hasta que los consumidores cambien sus preferencias.</span></p>
    <p><strong>4) Su trabajo ha seguido evolucionando hacia la comunidad cafetera en general. &iquest;Puede compartir algunas historias inspiradoras al respecto?</strong></p>
    <p><span style="font-weight: 400;">En el noroeste de Pichincha fuimos los pioneros en el cultivo de caf&eacute;s especiales en una zona no productora de caf&eacute; (Las primeras cosechas de la finca Las Tolas son de 1999). Hoy existen m&aacute;s de 200 productores en esta zona que vinieron apostando por el cultivo. Hemos sacado el primer material con el que empezamos los experimentos.</span></p>
    <p><span style="font-weight: 400;">Hoy seguimos investigando (t&eacute;cnicas "suaves"), observando (conceptos agroforestales) e innovando (fermentaciones controladas) para compartir estas experiencias con la comunidad cafetera. Obviamente, incluyo en esta comunidad a toda la cadena, incluso a los baristas, que no descansan para educar a los consumidores y ejercen una enorme presi&oacute;n sobre nosotros (los productores) para que no dejemos de proponer nuevas tendencias. As&iacute;, el mundo de los caf&eacute;s especiales se dinamiz&oacute; tremendamente hasta el punto de que, hoy en d&iacute;a, est&aacute; totalmente desvinculado del "granel" y del manejo de los &ldquo;commodities&rdquo;.</span></p>
    <p><strong>5) &iquest;Cu&aacute;les son las mejores pr&aacute;cticas para producir un caf&eacute; de calidad?</strong></p>
    <p><span style="font-weight: 400;">La mejor pr&aacute;ctica es sin duda la OBSERVACI&Oacute;N. La mayor&iacute;a de los productores saben de memoria los manuales de cultivo; sin embargo, no aplican toda la parte t&eacute;cnica que les recomienda porque deben enfrentar una serie de limitaciones propias, inherentes a las condiciones de sus plantaciones y sus econom&iacute;as. Por ello, los m&aacute;s eficientes son los que mejor han sabido adaptarse tanto al entorno como al mercado.</span></p>
    <p>&nbsp;</p>
    <p><strong>6) &iquest;C&oacute;mo conserva sus caf&eacute;s? &iquest;Qu&eacute; importancia tienen las buenas soluciones de envasado herm&eacute;tico para su negocio? &iquest;Hay marcas espec&iacute;ficas que prefiera?</strong></p>
    <p><span style="font-weight: 400;">Nuestros caf&eacute;s se conservan en la finca tanto en pergamino como en cereza seca en bolsas Ecotact para permitir una mejor homogenizaci&oacute;n (que equivalente a un reposo en grandes tolvas) y evitar contaminaciones (hongos, moho, insectos) y variaciones de humedad. En los caf&eacute;s naturales, la posibilidad de almacenar varios meses sin cambios bruscos de condiciones permite un tremendo plus de envejecimiento tipo. Hoy en d&iacute;a, no creo que alg&uacute;n comprador de caf&eacute;s especiales no exija que se exporten en empaques herm&eacute;ticos. El envasado al vac&iacute;o, abandonado durante un tiempo, parece volver a convencer y podr&iacute;a ser una oportunidad para bajar a&uacute;n m&aacute;s el contenido unitario (de sacos de 69 Kg pasamos a 60 Kg, luego a 50 Kg y 25 Kg.) por debajo de los 20 Kg (los envases al vac&iacute;o de capacidad para 5-10-15, Kg pueden adecuarse a capacidad de los equipos de los peque&ntilde;os tostadores, anim&aacute;ndoles a comprar caf&eacute;s m&aacute;s caros en cantidades m&aacute;s peque&ntilde;as.</span></p>
    <p><strong>7) &iquest;Han notado alg&uacute;n cambio en el patr&oacute;n de consumo/demanda de caf&eacute; durante la pandemia?</strong></p>
    <p><span style="font-weight: 400;">Curiosamente, nuestros clientes nos han dicho que los caf&eacute;s m&aacute;s caros se han vendido muy bien. En los pa&iacute;ses consumidores, este efecto se debe a varios factores, principalmente evidentes durante el confinamiento:</span></p>
    <p><span style="font-weight: 400;">- Los consumidores tuvieron m&aacute;s tiempo para investigar y conocer acerca de los caf&eacute;s especiales; por lo que la elecci&oacute;n del caf&eacute; pas&oacute; por un proceso de selecci&oacute;n m&aacute;s profundo que el habitual;</span></p>
    <p><span style="font-weight: 400;">- Los consumidores preguntaron m&aacute;s por sus caf&eacute;s en l&iacute;nea y pudieron acceder a una oferta mucho m&aacute;s amplia que en un supermercado, descubriendo las opciones de trazabilidad tan avanzadas;</span></p>
    <p><span style="font-weight: 400;">- Los consumidores ahorraron dinero al no consumir fuera de casa y no dudaron en pagar m&aacute;s por sus caf&eacute;s y dar m&aacute;s importancia a la calidad;</span></p>
    <p>&nbsp;</p>
    <p><strong>8) &iquest;Cu&aacute;les son algunos de los retos a los que se han enfrentado como productores de caf&eacute;s especiales debido a la pandemia?</strong></p>
    <p><span style="font-weight: 400;">En medio de lo que debi&oacute; ser una verdadera tragedia para muchas personas, podemos considerarnos privilegiados en nuestra actividad y negocio; no dejamos de producir, no dejamos de vender.</span></p>
    <p><span style="font-weight: 400;">Las cosas se complicaron bastante en los tr&aacute;mites administrativos y las fuentes de financiaci&oacute;n se secaron, lo que hizo muy dif&iacute;cil la gesti&oacute;n econ&oacute;mica. En ese momento, el apoyo de nuestros aliados del nivel de m&aacute;s abajo en la cadena fue crucial.</span></p>
    <p><strong>9) &iquest;C&oacute;mo cree que el envasado herm&eacute;tico ayuda al sector del caf&eacute; en estos tiempos dif&iacute;ciles?</strong></p>
    <p><span style="font-weight: 400;">No creo que tenga una influencia t&eacute;cnica significativa en la seguridad sanitaria debido a los tiempos de almacenamiento y a las extremas precauciones que se toman en las fincas, pero, sin duda, debe tranquilizar a las personas que deben manipular el producto en destino.</span></p>
    <p><span style="font-weight: 400;">Por otro lado, al ampliarse los plazos de todos los tr&aacute;mites, poder conservar el caf&eacute; en mejores condiciones es fundamental y los productores deber&iacute;an pensar seriamente en utilizar envases herm&eacute;ticos en la conservaci&oacute;n en finca y no s&oacute;lo como una exigencia del mercado para la exportaci&oacute;n.</span></p>
        ',
    '5' => '<p><span style="font-weight: 400;">La palabra sostenible de acuerdo a su significado del diccionario se refiere a "conservar un equilibrio ecol&oacute;gico evitando el agotamiento de los recursos naturales". A lo largo de los a&ntilde;os este equilibrio se ha ido rompiendo y nuestro medio ambiente est&aacute; ahora muy amenazado. Las Naciones Unidas, junto con otras empresas sociales y organizaciones de investigaci&oacute;n, han dado un paso adelante para educar a la gente sobre las adversidades de nuestro entorno y la creciente necesidad de adoptar un estilo de vida m&aacute;s respetuoso con el medio ambiente y ecol&oacute;gicamente sostenible. Como parte de la agenda 2030, la ONU ha adoptado algunas medidas y hace hincapi&eacute; en un enfoque hol&iacute;stico para lograr un desarrollo sostenible para todos para un crecimiento sostenible.</span></p>
    <ul>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Para 2030, mejorar las infraestructuras y modernizar las industrias para hacerlas sostenibles, con una mayor eficiencia en el uso de los recursos y una mayor adopci&oacute;n de tecnolog&iacute;as y procesos industriales limpios y respetuosos con el medio ambiente, tomando todos los pa&iacute;ses medidas de acuerdo con sus respectivas capacidades</span></li>
    </ul>
    <p><span style="font-weight: 400;"><br /><br /></span></p>
    <ul>
    <li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Mejorar progresivamente, hasta 2030, la eficiencia global de los recursos en el consumo y la producci&oacute;n y esforzarse por desvincular el crecimiento econ&oacute;mico de la degradaci&oacute;n medioambiental, en un marco de diez a&ntilde;os y de acuerdo con los programas existentes sobre consumo y producci&oacute;n sostenibles, con los pa&iacute;ses desarrollados a la cabeza.</span></li>
    </ul>
    <p>&nbsp;</p>
    <p><span style="font-weight: 400;">Muchos cient&iacute;ficos medioambientales opinan que, si no se frena el consumo excesivo de recursos, la civilizaci&oacute;n moderna se derrumbar&aacute; al igual que las antiguas civilizaciones que no aplicaron un uso sostenible de sus recursos.</span></p>
    <p><span style="font-weight: 400;">Creemos que cada esfuerzo cuenta y es un paso hacia un futuro m&aacute;s verde. Debido a nuestro entorno y asumiendo el compromiso de protegerlo, Ecotact se compromete con un comercio sostenible y ecol&oacute;gico. Al estar en el ADN de la organizaci&oacute;n, Ecotact cree en la reducci&oacute;n de la huella de carbono y en la conservaci&oacute;n del medio ambiente para un futuro mejor. Con este fin, Ecotact se ha aliado con diferentes organismos en distintas partes del mundo para gestionar los residuos de forma eficaz y, muy recientemente, ha lanzado una iniciativa para reciclar sus bolsas herm&eacute;ticas.</span></p>
    <p><strong>&iquest;C&oacute;mo funciona?</strong></p>
    <p><span style="font-weight: 400;">Las bolsas de pl&aacute;stico herm&eacute;tico multicapa de Ecotact son 100% reciclables. Como organizaci&oacute;n global responsable, creemos en la sostenibilidad y la econom&iacute;a circular. Hemos invertido no s&oacute;lo en la creaci&oacute;n de productos confiables y responsables, sino tambi&eacute;n en la creaci&oacute;n de procesos de reciclaje, lo que permite a cada uno de los usuarios de nuestro producto formar parte del movimiento global de reducci&oacute;n de la huella de carbono. Hemos creado una infraestructura global con una ventanilla &uacute;nica para la recogida y el reciclaje real de los productos Ecotact. Tenemos socios globales en varias partes del mundo que nos ayudan a recogerlos y reciclarlos a un coste insignificante o nulo para el usuario.</span></p>
    <p>&nbsp;</p>
    <p><strong>Pasos para pedir su caja de reciclaje Ecotact</strong></p>
    <p><span style="font-weight: 400;">&iexcl;Env&iacute;enos su caja rellena para su reciclaje! Seamos un habitante responsable y adoptemos m&eacute;todos de reciclaje para preservar nuestro medio ambiente en los a&ntilde;os venideros. Para m&aacute;s informaci&oacute;n, haga clic aqu&iacute;.</span></p>
    ',
    '6' => '<p><span style="font-weight: 400;">Existen varios tipos de procesamiento del caf&eacute; verde, siendo el natural y el honey los m&aacute;s complejos. Este blog tiene como objetivo restablecer la informaci&oacute;n para la correcta comprensi&oacute;n de los procesos. Uno podr&iacute;a preguntarse qu&eacute; son exactamente y c&oacute;mo se lleva a cabo el proceso. A continuaci&oacute;n, le ofrecemos una explicaci&oacute;n exhaustiva para saciar su curiosidad. El proceso natural, tambi&eacute;n conocido como proceso seco, es un proceso b&aacute;sico que se origin&oacute; en Etiop&iacute;a. Se procesa dejando la fruta en el grano mientras este se seca. Aunque necesita menos inversi&oacute;n, sigue requiriendo ciertas condiciones clim&aacute;ticas para garantizar el secado del fruto y la semilla a tiempo. El proceso de recolecci&oacute;n es muy exigente para la producci&oacute;n de Specialty grade Naturals, ya que la masa debe ser extremadamente homog&eacute;nea, para garantizar un producto con el sabor y las condiciones adecuadas. El proceso de secado implica un proceso organizado y cient&iacute;fico, donde se registran los porcentajes de humedad y peso hasta que los caf&eacute;s alcanzan el punto ideal y se almacenan. A diferencia del caf&eacute; lavado, el caf&eacute; Natural tiene una actividad metab&oacute;lica a lo largo del tiempo y almacenado donde principalmente los hongos, son los que permiten una mejor calidad de los granos, ya que este metabolismo proporciona a los granos verdes mejores precursores de sabor y olor para que los tostadores trabajen con ellos. Este proceso tiene el potencial de crear los caf&eacute;s m&aacute;s sabrosos. Por eso los naturales almacenados, tienen tendencia a tener sabores m&aacute;s complejos y agradables despu&eacute;s de 4-6 meses de almacenamiento dentro de las bolsas ECOTACT.</span></p>
    <p><span style="font-weight: 400;">&nbsp;Por otro lado, los caf&eacute;s procesados como semilavados est&aacute;n a medio camino entre un caf&eacute; lavado y un caf&eacute; de proceso natural. El nombre &ldquo;honey&rdquo; viene en realidad de lo pegajosos que se vuelven los granos durante el procesado. Es afrutado, pero no de forma tan exagerada como algunos naturales. Suele tener una acidez m&aacute;s balanceada con notas afrutadas maduras m&aacute;s que los caf&eacute;s lavados, con un dulzor intenso y una sensaci&oacute;n compleja en boca. Tienen un proceso de selecci&oacute;n menos complejo, ya que la ventana de oportunidad para la cosecha es un poco menos estrecha; desafortunadamente los caf&eacute;s honey son m&aacute;s complejos de producir, ya que la variabilidad de las condiciones ambientales puede afectar la consistencia de ese tipo de proceso de manera m&aacute;s dram&aacute;tica. El caf&eacute; honey se pone a secar sin lavar el muc&iacute;lago, haciendo que el pergamino se manche y confiriendo el nombre del caf&eacute; de negro a rojo a rubio, etc. Una vez que el caf&eacute; se ha secado, el almacenamiento dentro de las bolsas ECOTACT permitir&aacute; una mayor actividad metab&oacute;lica, de nuevo relacionada con los hongos (beneficiosa) que con el tiempo potenciar&aacute; la disponibilidad de precursores de sabor y olor que mejorar&aacute;n el caf&eacute; para que el tostador lo exprese. Como sistema de almacenamiento de Pergamino en la propia finca, recomendamos a nuestros productores que mantengan sus caf&eacute;s debidamente secados dentro de las bolsas ECOTACT para evitar la reabsorci&oacute;n de agua y la exposici&oacute;n al ox&iacute;geno, y extender la calidad y el tiempo de supervivencia de sus cosechas. El procesamiento del caf&eacute; es una parte integral de la industria, pero rara vez se habla de &eacute;l. Es el paso m&aacute;s importante para obtener el mejor sabor en su taza cada ma&ntilde;ana.</span></p>
        ',
    '7' => '<p><span style="font-weight: 400;">Hablamos con el Sr. Carlon Melen sobre diversas t&eacute;cnicas de producci&oacute;n de caf&eacute; y profundizamos en la sostenibilidad de estos productos. Hablamos ampliamente de 4 temas principales en torno a la producci&oacute;n de caf&eacute; y obtuvimos una visi&oacute;n de la industria por parte del propio experto en la materia. Sigamos leyendo</span></p>
    <p><strong>&iquest;Cu&aacute;les son los beneficios ecol&oacute;gicos de la despulpadora en seco y c&oacute;mo surgi&oacute;?</strong></p>
    <p><span style="font-weight: 400;">Bueno, en aquella &eacute;poca no ten&iacute;a suficiente dinero para comprar una de esas grandes m&aacute;quinas industriales y &eacute;stas costaban una fortuna debido a la cantidad de agua que consum&iacute;an para pelar los granos perfectamente. S&iacute;, seg&uacute;n la p&aacute;gina web de la Asociaci&oacute;n de Caf&eacute;s Especiales de Estados Unidos, especifica que por cada kilo de granos verdes que producimos a trav&eacute;s de la m&aacute;quina normal, estamos utilizando 10.000 litros de agua. De ah&iacute; naci&oacute; mi idea de no utilizar ni una sola gota de agua con esta m&aacute;quina. Eso lo cambia todo. Ahora, con uno de estos aparatos podemos producir 17 toneladas de grano verdes o, digamos, un contenedor.</span></p>
    <p><strong>&iquest;Utilizan el medidor de grados Brix para recoger las cerezas adecuadas?</strong></p>
    <p><span style="font-weight: 400;">Utilizamos el medidor de grados Brix dos veces para recoger las cerezas. Comprobamos el nivel de los grados Brix en la finca y luego vamos a recoger las cerezas de caf&eacute;, despu&eacute;s nos tarda entre 3 y 4 horas en llevarlas al molino, donde tenemos las m&aacute;quinas. Dependiendo del tiempo que haga ese d&iacute;a, el caf&eacute; puede cambiar un poco de color. As&iacute; que volvemos a comprobarlo y, en funci&oacute;n del resultado, decidimos si vamos a realizar un proceso de lavado.</span></p>
    <p><strong>H&aacute;blenos de su experiencia en el cultivo de caf&eacute; en Jap&oacute;n</strong></p>
    <p><span style="font-weight: 400;">Jap&oacute;n tiene mucho m&aacute;s acceso a la tecnolog&iacute;a y a los m&eacute;todos. As&iacute; que han aplicado su experiencia en tecnolog&iacute;a tambi&eacute;n en la producci&oacute;n de caf&eacute;. Lo que intentamos hacer es un intercambio de informaci&oacute;n. Aqu&iacute;, en Jap&oacute;n, debido al paisaje y a las ubicaciones, al clima tropical y a la altitud, Jap&oacute;n es un actor emergente en el negocio del caf&eacute;. Pero, por mucho que se est&eacute; convirtiendo en un actor global, nunca compromete la calidad. Apuestan por la calidad con peque&ntilde;as cantidades.</span></p>
    <p>&nbsp;</p>
    <p><strong>&iquest;Qu&eacute; opina de mantener el caf&eacute; verde intacto con Ecotact?</strong></p>
    <p><span style="font-weight: 400;">Las bolsas Ecotact son sostenibles, econ&oacute;micas y, lo que es m&aacute;s importante, respetuosas con el medio ambiente. Mantienen intacto el sabor de los granos, prolongando as&iacute; la frescura y la durabilidad.</span></p>
    <p><strong>&iquest;C&oacute;mo ha sido su experiencia con Ecotact?</strong></p>
    <p><span style="font-weight: 400;">Mi experiencia con Ecotact es incre&iacute;ble. Creo que he hecho un gran trabajo como promotor de las bolsas Ecotact, porque dondequiera que voy, simplemente menciono las bolsas y les digo que necesitan usar bolsas como estas porque les ayudar&aacute;n a conservar, preservar o tambi&eacute;n podr&iacute;an ayudar a mejorar la calidad. El envasado al vac&iacute;o es muy importante para la conservaci&oacute;n y tenemos muy buenos resultados con las bolsas Ecotact. Dependiendo de la calidad del caf&eacute;, y de lo que quieran los clientes/consumidores, lo envasamos al vac&iacute;o y lo ponemos en cajas y lo enviamos por aire.</span></p>
    <p><span style="font-weight: 400;">Aqu&iacute; est&aacute; nuestra detallada entrevista en v&iacute;deo con el Sr. Carlos Melen. No deje de verla.</span></p>
    ',
    '8' => '<p><span style="font-weight: 400;">Seg&uacute;n usted, </span><strong>&iquest;qu&eacute; cambios se han producido en la industria del caf&eacute; debido a COVID-19? &iquest;Ha repercutido en la forma de operar de Opal Coffee?</strong></p>
    <p><span style="font-weight: 400;">COVID-19 ha tenido un impacto en Opal Coffee de muchas maneras, en la forma en que se llevan a cabo los negocios. Esto incluye varios cambios en la industria. La mayor&iacute;a de los compradores prefieren mantener sus m&eacute;todos de compra anteriores. Mientras el volumen disminuye en el segmento de las especialidades, se ha producido un aumento en el segmento comercial. Con el cambio de los tiempos, los m&eacute;todos tecnol&oacute;gicos tambi&eacute;n se han acelerado.</span></p>
    <p><strong>&iquest;Ha afectado esto a la demanda de caf&eacute; en los &uacute;ltimos meses?</strong></p>
    <p><span style="font-weight: 400;">El volumen ha disminuido en el segmento de especialidades, mientras que ha aumentado en el segmento comercial.</span></p>
    <p><span style="font-weight: 400;">Opal Coffee opera a nivel mundial. Algunos de sus mercados se han visto afectados de forma moderada y otros se han visto afectados en gran medida por el COVID19. &iquest;Qu&eacute; impacto tiene el mercado del caf&eacute; en cada una de estas regiones? Y el camino a seguir.</span></p>
    <p><span style="font-weight: 400;">COVID-19 ha impactado de forma diferente, en particular a aquellos negocios que han sido golpeados fuertemente en su volumen. Dado que sus costes fijos permanecen constantes, la mayor&iacute;a de los tostadores optan por reducir el coste de las compras para aumentar su margen bruto y poder pagar los gastos generales fijos.</span></p>
    <p>&nbsp;</p>
    <p><span style="font-weight: 400;">Aprovisionamiento de caf&eacute; - </span><strong>&iquest;En qu&eacute; medida es diferente el aprovisionamiento de caf&eacute; en estos tiempos dif&iacute;ciles en los que no es posible visitar el origen? &iquest;En qu&eacute; medida es diferente el abastecimiento de caf&eacute; especial por parte de la industria?</strong></p>
    <p><span style="font-weight: 400;">Hemos modificado nuestras metodolog&iacute;as anteriores y las relaciones que hemos fomentado. Los proveedores est&aacute;n enviando las muestras en lugar de que nosotros visitemos el origen y, en consecuencia, ha habido algunos retrasos en el proceso de toma de decisiones. Hemos aprovechado este tiempo para establecer nuevas relaciones con nuestros proveedores, ya que antes no ten&iacute;amos la oportunidad de hacerlo.</span></p>
    <p><strong>&iquest;Cu&aacute;l ha sido el impacto en el precio del caf&eacute; verde, que ya estaba en niveles hist&oacute;ricamente bajos?</strong></p>
    <p><span style="font-weight: 400;">El precio ha estado fluctuando durante mucho tiempo y no ha afectado mucho al precio actual.</span></p>
    <p><strong>&iquest;La depreciaci&oacute;n de la moneda de la mayor&iacute;a de los pa&iacute;ses productores ha ayudado a los agricultores locales y a los exportadores de caf&eacute;?</strong></p>
    <p><span style="font-weight: 400;">La depreciaci&oacute;n de la moneda ha afectado sin duda a los peque&ntilde;os productores, pero como la depreciaci&oacute;n de la moneda suele reflejarse en el movimiento del mercado de Nueva York, el precio final de entrega se mantiene m&aacute;s o menos igual.</span></p>
    <p><strong>&iquest;Qu&eacute; puntos hay que tener en cuenta para almacenar los granos de caf&eacute; verde?</strong></p>
    <p><span style="font-weight: 400;">Cuando se almacena el caf&eacute; hay que hacerlo siempre en un lugar fresco y seco. Adem&aacute;s, debe almacenarse en bolsas herm&eacute;ticas Ecotact para prolongar su vida &uacute;til.</span></p>
    <p><strong>&iquest;Qu&eacute; medidas toman para garantizar que la calidad del caf&eacute; verde se mantenga durante el tr&aacute;nsito o el almacenamiento?</strong></p>
    <p><span style="font-weight: 400;">Una de las formas m&aacute;s eficaces de mantener la calidad y prolongar su vida &uacute;til es adoptar los envases herm&eacute;ticos Ecotact para nuestra gama de caf&eacute;s especiales.</span></p>
    <p><strong>La industria del caf&eacute; ha evolucionado a lo largo de los a&ntilde;os. &iquest;Podr&iacute;a decirnos en qu&eacute; se ha inspirado?</strong></p>
    <p><span style="font-weight: 400;">A lo largo de los a&ntilde;os ha evolucionado mucho, por ejemplo, el comercio directo se ha hecho muy popular, aunque el "verdadero" comercio directo con transparencia sigue siendo dif&iacute;cil de establecer. Por desgracia, los mercados comerciales siguen dominados por los mismos actores principales.</span></p>
        ',
    '9' => '<p><strong>&iquest;C&oacute;mo ha afectado la pandemia de COVID 19 a la industria del caf&eacute;?&nbsp;</strong></p>
    <p><span style="font-weight: 400;">A corto plazo, nuestros clientes informaron de que el negocio hab&iacute;a disminuido entre un 75 y un 95%.&nbsp; Ha empezado a recuperarse poco a poco, pero creo que los efectos a largo plazo est&aacute;n por ver.</span></p>
    <p><strong>&iquest;Cu&aacute;les son los cambios que prev&eacute; en t&eacute;rminos de pr&aacute;cticas comerciales que van a cambiar y evolucionar como consecuencia?&nbsp;</strong></p>
    <p><span style="font-weight: 400;">Esa es una pregunta complicada.&nbsp; Creo que las respuestas variar&aacute;n en funci&oacute;n de la empresa, de sus dirigentes y de c&oacute;mo se haya gestionado la situaci&oacute;n.&nbsp; S&eacute; que, para mi propia empresa, lo vemos como un momento decisivo en nuestra historia en el que tuvimos la oportunidad de retirarnos de muchos contratos de compra en favor de la protecci&oacute;n de nuestros propios intereses, pero en cambio optamos por seguir adelante con cada compra a pesar del riesgo.&nbsp; Nuestros clientes han respondido favorablemente a esa medida y quieren apoyar a una empresa que quiere apoyar a los agricultores y socios en origen.</span></p>
    <p><strong>&iquest;Ha notado un cambio en el patr&oacute;n de consumo/demanda de caf&eacute; durante la pandemia?</strong></p>
    <p><span style="font-weight: 400;">Sin lugar a dudas.&nbsp; Lo que m&aacute;s han comunicado la mayor&iacute;a de los tostadores es que sus ventas por Internet se han disparado.&nbsp; Algunos han informado de un aumento de hasta un 2500%.</span></p>
    <p><strong>&iquest;Cu&aacute;les son los controles que sugieren a la hora de abastecerse de caf&eacute; de calidad?</strong></p>
    <p><span style="font-weight: 400;">En todos los or&iacute;genes, medimos la actividad del agua, el contenido de humedad, el rendimiento, los rayos UV y la puntuaci&oacute;n en taza.&nbsp; Para ser sinceros, aunque la puntuaci&oacute;n en taza es ciertamente importante, optamos por no comprar caf&eacute;s que tengan una buena taza pero que no se ajusten a las dem&aacute;s &aacute;reas.</span></p>
    <p><strong>&iquest;Cu&aacute;l es el clima ideal para el almacenamiento de caf&eacute; verde?</strong></p>
    <p><span style="font-weight: 400;">&iexcl;Lo ideal ser&iacute;a temperaturas de congelaci&oacute;n con baja humedad&hellip; jaja!!&nbsp; pero me doy cuenta de que eso no es realista para muchos. Dicho esto, por debajo de 60 grados F&deg; parece mantener el buen caf&eacute; fresco durante bastante tiempo. Digo "buen caf&eacute;" porque el caf&eacute; malo se desvanecer&aacute; m&aacute;s r&aacute;pidamente sin importar la temperatura a la que se almacene por encima de &iquest;</span><strong>Deber&iacute;a el almacenamiento de caf&eacute; verde ser diferente del almacenamiento de caf&eacute; tostado para mantenerlos frescos?</strong></p>
    <p><strong>&iquest;Debe el almacenamiento del caf&eacute; verde ser diferente del almacenamiento del caf&eacute; tostado para mantenerlo fresco?</strong></p>
    <p><span style="font-weight: 400;">Para ser sinceros, las temperaturas ideales para ambos son bastante similares. Mientras que la congelaci&oacute;n en un recipiente sellado al vac&iacute;o es ideal para ambos, cuanto m&aacute;s calor haga, m&aacute;s r&aacute;pido se desvanecer&aacute; cada uno, aunque el caf&eacute; tostado obviamente se desvanece a un ritmo mucho m&aacute;s r&aacute;pido que el verde.</span></p>
    <p><strong>Seg&uacute;n Ud., &iquest;Cu&aacute;les son las mejores soluciones de almacenamiento para el caf&eacute;?</strong></p>
    <p><span style="font-weight: 400;">En t&eacute;rminos pr&aacute;cticos, si todo nuestro caf&eacute; verde se almacenara a una temperatura constante de 60 grados F&deg; a una humedad baja y nada fluctuara, yo ser&iacute;a feliz. Eso, por supuesto, suponiendo que los caf&eacute;s se almacenaran en bolsas herm&eacute;ticas o en cajas selladas al vac&iacute;o.</span></p>
    <p><strong>&iquest;C&oacute;mo cree que el envasado herm&eacute;tico est&aacute; ayudando a la industria del caf&eacute; en estos tiempos dif&iacute;ciles?</strong></p>
    <p><span style="font-weight: 400;">Creo que muchos tostadores y comercializadores van a tener que guardar los caf&eacute;s durante mucho m&aacute;s tiempo del previsto, y el envasado herm&eacute;tico ayudar&aacute; sin duda a conservar la calidad y, por tanto, el valor durante los pr&oacute;ximos, probablemente dif&iacute;ciles, meses.</span></p>
    <p><strong>&iquest;Alguna palabra de inspiraci&oacute;n sobre el caf&eacute; y su relaci&oacute;n con los consumidores?</strong></p>
    <p><span style="font-weight: 400;">Estos &uacute;ltimos meses han sido los m&aacute;s dif&iacute;ciles en muchas de nuestras carreras, pero con socios fuertes en todos los eslabones de la cadena de suministro, creo que todos podemos encontrar formas de capear el temporal juntos.</span></p>
        ',
    '10' => '<p><strong>&iquest;Cu&aacute;l es el escenario global de la plantaci&oacute;n de caf&eacute;?</strong></p>
    <p><span style="font-weight: 400;">En t&eacute;rminos generales, el precio del caf&eacute; sigue siendo el mayor desaf&iacute;o. Sin embargo, esto afecta a distintos tipos de productores de manera diferente. Con la amenaza de COVID 19 es dif&iacute;cil saber exactamente qu&eacute; va a pasar con las plantaciones, ya que no s&oacute;lo el precio, sino tambi&eacute;n la demanda general de caf&eacute;s especiales est&aacute; sufriendo un golpe, ya que las tiendas especializadas siguen cerradas. Esto afecta a las explotaciones comerciales a gran escala, as&iacute; como a las especializadas y a todo lo que est&aacute; en medio. Parece ser la tormenta perfecta.</span></p>
    <p><span style="font-weight: 400;">Actualmente mi principal preocupaci&oacute;n es tanto la calidad como la cantidad de las futuras cosechas. Tras varios a&ntilde;os de malos precios, la calidad se ver&aacute; inevitablemente afectada. Si un peque&ntilde;o productor vende por debajo de su coste de producci&oacute;n, buscar&aacute; recortar costes en fertilizaci&oacute;n, pruebas de suelo, entre otros. En consecuencia, la calidad tambi&eacute;n descender&aacute; inevitablemente.</span></p>
    <p><span style="font-weight: 400;">En mi opini&oacute;n, estamos en el segundo a&ntilde;o de precios bajos, por lo que la presi&oacute;n est&aacute; subiendo y esto es ahora evidente. Algunos productores empiezan a sacrificar la calidad como resultado.</span></p>
    <p><strong>&iquest;C&oacute;mo est&aacute; cambiando la industria del caf&eacute;? &iquest;Cu&aacute;les son los cambios que ha experimentado la industria del caf&eacute; en las &uacute;ltimas d&eacute;cadas?</strong></p>
    <p><span style="font-weight: 400;">Hay mucha intenci&oacute;n de probar cosas nuevas, si se compara la mentalidad actual de un productor de caf&eacute; con respecto al pasado. La tradici&oacute;n es un aspecto muy interesante de lo que ahora est&aacute; cambiando. Despu&eacute;s de todo, &iquest;qu&eacute; es la tradici&oacute;n? &iquest;Por qu&eacute; es tan dif&iacute;cil romperla y hacer lo contrario? Alejarse de la tradici&oacute;n siempre implica un riesgo. En la mayor&iacute;a de los casos es necesario y supone un gran progreso. Siempre hay que invertir para obtener buenos resultados. Todo logro requiere un primer intento potencial que fracasar&aacute;.</span></p>
    <p><span style="font-weight: 400;">Este es un tema muy amplio de debate. Es algo que se puede analizar desde la perspectiva del "nicho de mercado". Hay sectores del caf&eacute; que no est&aacute;n sujetos a este problema de precios.&nbsp; Hay "nichos" en los que la calidad es el aspecto definitorio.</span></p>
    <p><span style="font-weight: 400;">A medida que estos nichos se han ido desarrollando, el consumidor final ha sabido apreciar estos caf&eacute;s que tienen claramente un valor diferente y se atreve a pagar por cosas nuevas.</span></p>
    <p><span style="font-weight: 400;">As&iacute; que, si quieres innovar, debes arriesgar. &iquest;Y por qu&eacute; arriesgar los resultados seguros que est&aacute;s acostumbrado a conseguir? Porque el mercado lo est&aacute; exigiendo y est&aacute; premiando este riesgo. El mercado est&aacute; premiando la calidad para esos perfiles de copa, y esta nueva demanda de calidad permite a los agricultores tener un presupuesto para probar nuevos procesos y t&eacute;cnicas, para comprar nueva maquinaria, conseguir nuevas variedades, investigar m&aacute;s en t&eacute;rminos de fertilizaci&oacute;n.</span></p>
    <p><span style="font-weight: 400;">Siempre es interesante analizar la tradici&oacute;n porque es una forma conocida de obtener resultados. Por lo tanto, es una apuesta segura. Por eso probablemente sea tan dif&iacute;cil dejar la tradici&oacute;n. Pero, por otro lado, los precios no son muy atractivos cuando se trata de un caf&eacute; "normal" o "tradicional". Son tiempos muy interesantes los que vivimos, ya que se est&aacute; innovando mucho.&nbsp;&nbsp;</span></p>
    <p><strong>&iquest;Cu&aacute;les son las medidas para producir una cosecha de la mejor calidad?</strong></p>
    <p><span style="font-weight: 400;">Hay varios aspectos que medir cuando se trata de producir grandes caf&eacute;s.</span></p>
    <p><span style="font-weight: 400;">Intentamos mantener ocupado nuestro departamento de I+D. A grandes rasgos, controlamos principalmente varios puntos de datos para una serie de varietales a lo largo del a&ntilde;o, y tambi&eacute;n probamos nuevos m&eacute;todos de procesamiento durante la cosecha. Probamos constantemente nuevas variedades para ver c&oacute;mo funcionan en nuestros suelos, altitudes y climas. Medimos absolutamente todo: la composici&oacute;n del suelo, la composici&oacute;n de las hojas, los nutrientes que absorben las plantas, los que faltan, la cantidad de lluvia durante todo el a&ntilde;o. Este tipo de trabajo se har&aacute; de forma perpetua, para siempre.</span></p>
    <p><span style="font-weight: 400;">En cuanto a la productividad de la planta, buscamos medir la densidad de producci&oacute;n. &iquest;C&oacute;mo lo hacemos? Medimos el crecimiento de la planta en un lapso de tiempo determinado, la altura de la primera rama productiva, cu&aacute;ntas ramas productivas tenemos a 1 metro del suelo, cantidad de ramas productivas a 2 metros del suelo. A continuaci&oacute;n, empezamos a analizar los puntos productivos de una rama concreta, la distancia entre ellos, cu&aacute;ntos granos estamos obteniendo en ese punto productivo concreto. Despu&eacute;s de recopilar los datos, analizamos los resultados para determinar si esa planta o variedad en particular tiene un futuro prometedor en esa plantaci&oacute;n concreta. Despu&eacute;s de todo esto, el caf&eacute; en s&iacute; es catado y evaluado a nivel de calidad para determinar si es una variedad de inter&eacute;s para nuestra plantaci&oacute;n.</span></p>
    <p><span style="font-weight: 400;">A veces nos enfrentamos a ciertos dilemas con las nuevas variedades, porque no sabemos realmente c&oacute;mo van a reaccionar en determinadas circunstancias. As&iacute; que realizamos pruebas paralelas para medir nuestros resultados de forma m&aacute;s objetiva.</span></p>
    <p><strong>&iquest;Cu&aacute;les son los distintos puntos de control a la hora de almacenar?</strong></p>
    <p><span style="font-weight: 400;">Despu&eacute;s de procesar el caf&eacute;, comprobamos: los niveles de humedad, el rendimiento de la cosecha, el aspecto visual de los granos y los aspectos de la cata (atributos/defectos en la taza). Dependiendo del resultado, determinamos si el caf&eacute; tiene potencial para ser vendido como especial o para ser vendido como convencional. El muestreo es lo que hace que todos nuestros lotes sean 100% trazables.</span></p>
    <p><span style="font-weight: 400;">Una vez que el caf&eacute; se determina como especial seg&uacute;n su contenido &oacute;ptimo de humedad, lo dejamos reposar en sacos Ecotact hasta que estamos listos para descascararlo.&nbsp; Esto ayuda a que el caf&eacute; se estabilice y se asiente en su m&aacute;ximo potencial. Esto tambi&eacute;n nos permite ofrecer los caf&eacute;s y tener la seguridad de que la calidad se mantendr&aacute; bien almacenada hasta que estemos listos para el env&iacute;o.</span></p>
    <p><span style="font-weight: 400;">En muchos sentidos, la bolsa Ecotact le permite ganar tiempo. No s&oacute;lo con la conservaci&oacute;n de la calidad de la taza, sino tambi&eacute;n con el mantenimiento del aspecto visual ideal del caf&eacute;.</span></p>
    <p><strong>&iquest;Cu&aacute;les son los factores que deben determinar el tipo de envase?</strong></p>
    <p><span style="font-weight: 400;">En mi opini&oacute;n, el tipo de caf&eacute; determina el tipo de envase. Los caf&eacute;s de alta calidad se benefician de la protecci&oacute;n antes del procesamiento, ya que la bolsa Ecotact proporciona una barrera perfecta para los cambios de humedad, y esto permite que el caf&eacute; se asiente lentamente y sin interrupciones antes de ser finalmente procesado y enviado.</span></p>
    <p><span style="font-weight: 400;">Para las exportaciones: Me adapto a las necesidades de mis clientes. Trabajamos como siempre en el formato de 69 kg, pero tambi&eacute;n en el de 30-35 kg (cada vez m&aacute;s a menudo). Tambi&eacute;n hay una demanda ocasional de envasado al vac&iacute;o cuando se trata de caf&eacute;s de alta calidad.</span></p>
    <p><span style="font-weight: 400;">Suelo recomendar el vac&iacute;o para caf&eacute;s que se van a consumir lentamente o que est&aacute; previsto almacenar a largo plazo. Las bolsas Ecotact para el consumo a "corto" plazo hasta un a&ntilde;o completo con grandes resultados en la preservaci&oacute;n de la calidad de la taza y el aspecto f&iacute;sico general.</span></p>
    <p><strong>&iquest;Qu&eacute; impacto tendr&aacute; la industria del caf&eacute; a causa de la pandemia COVID 19 y el bloqueo?</strong></p>
    <p><span style="font-weight: 400;">Cambiar&aacute; la forma de llegar al consumidor final. Habr&aacute; reajustes en la forma de beber caf&eacute;, especialmente en casa. El consumo de caf&eacute; se est&aacute; reinventando para mucha gente.</span></p>
    <p><span style="font-weight: 400;">Como la gente tiene menos acceso a los caf&eacute;s de la calle, se encuentra en la situaci&oacute;n de tener que beberlo en casa. La gente ahora muele en casa, hay varios modelos de tostadores caseros que son m&aacute;s accesibles para todos. Los consumidores de caf&eacute; preparan m&aacute;s V60 y otros m&eacute;todos de vertido.</span></p>
    <p><span style="font-weight: 400;">Los caf&eacute;s de la calle y los peque&ntilde;os tostadores se est&aacute;n viendo afectados por esta crisis. Muchas de estas peque&ntilde;as cafeter&iacute;as est&aacute;n haciendo ahora principalmente entregas a domicilio de 1 libra de caf&eacute;s reci&eacute;n tostados. Otras empresas m&aacute;s grandes que venden en supermercados parecen estar un poco menos afectadas.</span></p>
    <p><span style="font-weight: 400;">En estos tiempos de incertidumbre, el distanciamiento social tambi&eacute;n est&aacute; perturbando el aspecto social de reunirse en una cafeter&iacute;a y tomar caf&eacute; juntos. Esta parte tambi&eacute;n es un poco desafortunada.</span></p>
    <p><strong>&iquest;C&oacute;mo van a ayudar los envases herm&eacute;ticos en esta grave situaci&oacute;n?</strong></p>
    <p><span style="font-weight: 400;">&iexcl;Ecotact me hace ganar tiempo! El envase herm&eacute;tico es lo que mantendr&aacute; mi caf&eacute; fresco todo el tiempo que necesite tenerlo almacenado: ya sea en mi almac&eacute;n de Guatemala o en el de EE.UU. (&iexcl;suele ocurrir!).</span></p>
    <p><span style="font-weight: 400;">Hemos encontrado grandes resultados utilizando las bolsas Ecotact de formas poco ortodoxas en las distintas etapas de la cadena de suministro del caf&eacute;. Ya sea para el almacenamiento en pergamino de origen, o para el env&iacute;o y almacenamiento de los granos verdes, utilizamos Ecotact para asegurar y prolongar la vida &uacute;til general de nuestros caf&eacute;s, manteniendo su alta calidad intacta para que nuestros clientes la disfruten en todo el mundo.</span></p>
        ',
    '11' => '<p><strong>&iquest;Cu&aacute;les son los hitos alcanzados por la India tras la liberalizaci&oacute;n del mercado indio del caf&eacute; en 1995?</strong></p>
    <p><span style="font-weight: 400;">La atenci&oacute;n a la calidad del caf&eacute; durante el procesamiento y la comercializaci&oacute;n ha aumentado enormemente. Los caficultores indios viajan ahora al extranjero y participan en conferencias y exposiciones de caf&eacute; para comercializarlo. Se han establecido v&iacute;nculos con el mercado, especialmente en lo que respecta a la comercializaci&oacute;n de relaciones. Tambi&eacute;n se ha producido una importante creaci&oacute;n de marca de los caf&eacute;s indios, lo que ha hecho que el mundo del caf&eacute; se d&eacute; cuenta de que la India produce excelentes caf&eacute;s Ar&aacute;bica y Robusta.</span></p>
    <p><strong>&iquest;C&oacute;mo est&aacute; cambiando la industria del caf&eacute; verde?</strong></p>
    <p><span style="font-weight: 400;">La trazabilidad y la certificaci&oacute;n son factores muy importantes en el mercado internacional del caf&eacute;.</span></p>
    <p><span style="font-weight: 400;">El mercadeo en Block Chain se est&aacute; llevando a cabo con ventas directas entre el comprador y el vendedor.</span></p>
    <p><span style="font-weight: 400;">Hoy en d&iacute;a, el caf&eacute; verde tambi&eacute;n se prepara de diferentes maneras, lo que aporta innovaci&oacute;n y tecnolog&iacute;a en las pr&aacute;cticas agr&iacute;colas y en las t&eacute;cnicas de procesamiento. Esto garantiza que la calidad de los granos verdes se desarrolle de tal manera que puedan utilizarse para preparar el caf&eacute; mediante diferentes metodolog&iacute;as de elaboraci&oacute;n. Las variantes de procesamiento en la preparaci&oacute;n de los granos verdes han pasado a primer plano.</span></p>
    <p><span style="font-weight: 400;">Los caf&eacute;s est&aacute;n abriendo sus puertas en or&iacute;genes productores como en China y Vietnam. De este modo, est&aacute;n contribuyendo a aumentar el consumo de caf&eacute; en los pa&iacute;ses productores y a cambiar, en cierta medida, la industria del caf&eacute; verde, que en el pasado abastec&iacute;a principalmente a los pa&iacute;ses consumidores de caf&eacute;.</span></p>
    <p><strong>&iquest;Cu&aacute;l es el papel de la India en el mercado mundial del caf&eacute;?</strong></p>
    <p><span style="font-weight: 400;">La India desempe&ntilde;a un papel bastante importante en el mercado del espresso, ya que los tostadores que tuestan para las mezclas de espresso descubren que nuestros caf&eacute;s indios pueden proporcionar una gran base para sus mezclas de espresso.</span></p>
    <p><span style="font-weight: 400;">La preparaci&oacute;n de micro-lotes, mediante la variaci&oacute;n de las t&eacute;cnicas de elaboraci&oacute;n, ha contribuido a proporcionar una cesta de sabores al mercado mundial del caf&eacute;.</span></p>
    <p><span style="font-weight: 400;">En la actualidad, el caf&eacute; Robusta representa el 40% del mercado mundial y el Robusta indio est&aacute; considerado como un Robusta de alta calidad en el mercado internacional, y se pagan precios superiores por nuestros caf&eacute;s Robusta de calidad.</span></p>
    <p><strong>&iquest;Qu&eacute; tama&ntilde;o tiene el mercado de exportaci&oacute;n del caf&eacute; indio?</strong></p>
    <p><span style="font-weight: 400;">El 75% de nuestro caf&eacute; se exporta.</span></p>
    <p><strong>&iquest;Qu&eacute; importancia tiene el envasado en la exportaci&oacute;n de caf&eacute;?</strong></p>
    <p><span style="font-weight: 400;">El envasado es un aspecto muy crucial para las exportaciones tanto de caf&eacute; verde como de caf&eacute; tostado. En el caso del caf&eacute; verde, el requisito m&aacute;s importante es preservar la calidad intr&iacute;nseca de los granos de caf&eacute; verde, especialmente para proteger y garantizar el contenido de humedad en los granos de caf&eacute;, para asegurar la vida &uacute;til y la retenci&oacute;n de la calidad. En el caso del caf&eacute; tostado y molido, es importante preservar los aromas y sabores del caf&eacute;, lo que requiere un buen material de envasado.</span></p>
    <p><span style="font-weight: 400;">Hoy en d&iacute;a, se utilizan empaques herm&eacute;ticos para envasar los granos de caf&eacute; verde con el fin de preservar su calidad intr&iacute;nseca.</span></p>
        ',
    '12' => '<p><span style="font-weight: 400;">Elegir el mejor envase para sus granos alimenticios es de suma importancia. Un envase herm&eacute;tico de varias capas garantiza que los granos est&eacute;n frescos durante m&aacute;s tiempo, lo que repercute directamente en el sabor de los granos o las jud&iacute;as. A la hora de seleccionar el envase adecuado, hay que tener siempre en cuenta que el envase no s&oacute;lo debe ayudar a conservar, sino tambi&eacute;n a proteger los granos de las influencias externas. A continuaci&oacute;n, se enumeran 5 formas en las que el envase herm&eacute;tico de 9 capas evita el deterioro de la calidad de los granos.</span></p>
    <p><span style="font-weight: 400;">1.Garantiza un nivel de humedad seguro: Si los granos est&aacute;n demasiado h&uacute;medos, existe la posibilidad de que se estropeen durante el almacenamiento, y si est&aacute;n demasiado secos, la reducci&oacute;n del peso provocar&aacute; la disminuci&oacute;n de su valor.&nbsp; El envase herm&eacute;tico de 9 capas ayuda a conservar el contenido de humedad perfecto.</span></p>
    <ol start="2">
    <li><span style="font-weight: 400;"> Protege de la humedad externa: Cuando la humedad entra en los granos, aparecen mohos e insectos. Este envase garantiza que los granos est&eacute;n protegidos de los da&ntilde;os causados por la humedad.</span></li>
    <li><span style="font-weight: 400;"> Tolera las altas temperaturas: Las altas temperaturas durante el proceso de almacenamiento o transporte pueden provocar la evaporaci&oacute;n de la humedad residual de los granos durante el d&iacute;a. A continuaci&oacute;n, se produce la condensaci&oacute;n y reabsorci&oacute;n de la humedad por la noche. Por el contrario, los envases herm&eacute;ticos de varias capas tienen una gran tolerancia a la temperatura (de -30 a 90 grados cent&iacute;grados).</span></li>
    <li><span style="font-weight: 400;"> Mantiene el aroma y el sabor: El muestreo de los granos de alimentos, especialmente del caf&eacute; verde, por parte de los comerciantes, tostadores y productores es uno de los ejercicios m&aacute;s cr&iacute;ticos. La mayor&iacute;a de las veces, las partes interesadas descuidan este hecho eligiendo envases de baja calidad, lo que se traduce en precios m&aacute;s bajos. Pero el envase herm&eacute;tico de 9 capas garantiza que el caf&eacute; se mantenga en condiciones de frescura en la granja con un nivel &oacute;ptimo de humedad y aroma.</span></li>
    <li><span style="font-weight: 400;"> Protege los alimentos sensibles y el contenido vitam&iacute;nico: Cada tipo de grano es diferente. Las soluciones herm&eacute;ticas fabricadas con tecnolog&iacute;a especial investigada para preservar la frescura natural de las fincas en los almacenes y durante su transporte, sin el uso de pesticidas e insecticidas, ayudan a mantener ilesos diversos granos despu&eacute;s de la cosecha.</span></li>
    </ol>
    <p><span style="font-weight: 400;">Las soluciones de envasado herm&eacute;tico de 9 capas de Ecotact son las soluciones definitivas para el envasado y almacenamiento de sus grano, especialmente para el caf&eacute; verde. Son extremadamente resistentes y tienen altas propiedades de barrera al ox&iacute;geno y a la humedad que sellan la frescura a lo largo de la cadena de suministro. Adem&aacute;s, son ecol&oacute;gicos y 100% reciclables.</span></p>
        ',
        
    '13' => '<p>Si usted es un tostador de peque&ntilde;a escala, tostador dom&eacute;stico o barista, las nuevas Troiseal Bags han sido desarrolladas exclusivamente para usted, teniendo en cuenta sus necesidades de almacenamiento. Sabemos exactamente lo que se necesita para conservar el caf&eacute; verde reci&eacute;n cultivado a mano y con mucha pasi&oacute;n.</p>
<p><strong>&iquest;Qu&eacute; es una Bolsa con triple sello?</strong></p>
<p>La bolsa Ecotact Troiseal tiene tres sellos secuenciales. "Tri" etimol&oacute;gicamente significa tres y, como sugiere el nombre, se puede sellar a la perfecci&oacute;n, y adem&aacute;s garantiza que la humedad no ingrese ni altere el contenido.</p>
<p><strong>&iquest;Por qu&eacute; utilizar las bolsas con Triple Sello? </strong></p>
<p>Los beneficios de adquirir las bolsas con triple protecci&oacute;n son:</p>
<ul>
<li>Han sido dise&ntilde;adas usando 9 capas de empaque herm&eacute;tico.</li>
<li>Es completamente a prueba de manipulaciones. Han sido dise&ntilde;adas para proteger el contenido.</li>
<li>Tambi&eacute;n se puede utilizar para almacenar ma&iacute;z, cebada, panela y cacao.</li>
<li>Las bolsas son transparentes permitir una clara visibilidad del contenido.</li>
<li>Son 100% reciclables y reutilizables, teniendo en consideraci&oacute;n el cuidado del medio ambiente ecol&oacute;gico.</li>
<li>Tiene 03 cierres secuenciales adhesivos de varias capas y permiten volver a sellar f&aacute;cilmente.</li>
<li>Tienen un asa en la parte superior para levantar y transportar f&aacute;cilmente.</li>
<li>Precios muy competitivos debido a la amplia demanda del producto.</li>
</ul>
<p>Para conocer m&aacute;s haz <a href="https://www.ecotactbags.com/eco-product/packaging/troiseal-bags">click</a> aqu&iacute;:</p>
<p>Adem&aacute;s de todas las ventajas mencionadas anteriormente, las bolsas de triple sellado est&aacute;n dise&ntilde;adas para ser completamente ecol&oacute;gicas para continuar el lema principal de Ecotact, que es preservar el medio ambiente para un futuro sostenible. Es ahora m&aacute;s que nunca que nuestro planeta necesita que demos un paso adelante y tomemos medidas para limpiar el desastre que la humanidad ha causado como resultado de la irresponsabilidad y negligencia. A&uacute;n queda mucho por hacer para devolver el equilibrio a nuestro ecosistema. Para obtener m&aacute;s informaci&oacute;n, deje un comentario a continuaci&oacute;n y nuestro equipo se comunicar&aacute; con usted pronto.</p>',
        
        'LEAVE A REPLY' => 'DEJA UNA RESPUESTA',
        'Your email address will not be published. Required fields are marked' => 'Su dirección de correo electrónico no será publicada. Los campos obligatorios están marcados *',
        'Comment' => 'Comentario',
        'Name' => 'Nombre',
        'Email' => 'Correo Electrónico',
        'Website' => 'Web',
        'Post comment' => 'Publicar Comentario',
        'Related blogs' => 'Blogs Relacionados',
        'All' => 'Todo',
        'Coffee' => 'Café',
        'Cocoa' => 'Cacao',
        'Storage & Packaging' => 'Almacenamiento y envasado',
        'News & Ecotact Community' => 'Noticias y Comunidad Ecotact',
        'Tuesday December 22, 2020' => 'Martes 22 de Diciembre de 2020',
        'Thursday November 26, 2020' => 'Jueves 26 de Noviembre de 2020',
        'Wednesday November 04, 2020' => 'Miércoles 04 de Noviembre de 2020',
        'Monday October 12, 2020' => 'Lunes 12 de octubre de 2020',
        'Saturday September 26, 2020' => 'Sábado 26 de Septiembre del 2020',
        'Tuesday September 22, 2020' => 'Martes 22 de Septiembre de 2020',
        'Friday September 25, 2020' => 'Viernes 25 de Septiembre de 2020',
        'Monday August 17, 2020' => 'Lunes 17 de Agosto de 2020',
        'Saturday July 04, 2020' => 'Sábado 04 de Julio de 2020',
        'Monday April 13, 2020' => 'Lunes 13 de Abril de 2020',
        'Thursday November 28, 2019' => 'Jueves 28 de Noviembre de 2019',
        'Friday August 09, 2019' => 'Viernes 9 de Agosto de 2019',
        'Thursday June 10, 2021' => 'Jueves 10 de junio de 2021',
        'Saturday May 29, 2021' => 'Sábado 29 de mayo de 2021',
        'Blogs' => 'Blogs',
        'Dive Deeper' => 'Lea más sobre el café verde y otras soluciones de almacenamiento y envasado de granos',
        'Author' => 'Autor',

];


