<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Home Page Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used during authentication for various
    | messages that we need to display to the user. You are free to modify
    | these language lines according to your application's requirements.
    |
    */

    'Terms' => 'Condiciones de Uso',
    'The' => 'Los términos "Nosotros" / "Nos" / "Nuestro" / "Negocio" / "Ecotact", individual y colectiva, se refieren a Aashirvad International y otros grupos, subsidiarias o compañías de inversión / empresas conjuntas / afiliadas permitidas y / o cesionarios. Los términos "Visitante" / "Usuario" se refieren a los usuarios. Este sitio web está destinado a ser utilizado por adultos mayores de 18 años. Si no es un adulto, aunque puede consultar nuestro sitio web, no debe registrarse ni enviarnos información personal. No recopilamos a sabiendas  información de menores. En caso de incumplimiento por parte del menor, el padre o tutor será responsable de compensar cualquier daño que surja de dicho uso indebido por parte del menor. Este sitio web es propiedad y está operado por Ecotact, y tiene su domicilio comercial principal en 878, S P Mukherjee Marg, Delhi 110 006, India. Esta página establece los términos y condiciones bajo los cuales usted (Visitante) puede visitar este Sitio web ("Sitio web"). Con solo acceder o utilizar el sitio web, usted reconoce, sin limitación o calificación, estar sujeto a estos Términos de uso y a las políticas, ya sea que haya leído las mismas, o no. Si no acepta los términos y condiciones establecidos aquí, le pediremos que se retire del sitio. La empresa, cualquiera de sus divisiones comerciales y / o sus subsidiarias, compañías asociadas o subsidiarias de subsidiarias u otras compañías de inversión (en la India o en el extranjero) se reservan sus respectivos derechos para revisar estos Términos de Uso en cualquier momento mediante la actualización de esta publicación. Nos reservamos el derecho de cambiar estos términos y condiciones de vez en cuando sin ninguna obligación de informarle y es su responsabilidad revisarlos con la mayor frecuencia posible. Estos Términos de Uso son efectivos a menos que usted o Ecotact los rescindan. Puede rescindir en cualquier momento, siempre que deje de utilizar este sitio web. Ecotact puede rescindir los Términos de Uso en cualquier momento y puede hacerlo sin previo aviso y, en consecuencia, denegarle el acceso al sitio web, sin ninguna responsabilidad hacia el sitio web.',
    'Intellectual' => 'Propiedad Intellectual',
    'All' => 'Todos los nombres, logotipos y todos los productos y servicios relacionados, marcas de diseño y lemas, son marcas comerciales registradas y no registradas de Ecotact o utilizadas bajo licencia o autorización por Ecotact y / o sus entidades asociadas. Todos los derechos, incluidos los derechos de autor, en este sitio web, son propiedad o están autorizados por Ecotact. El acceso a este sitio web no confiere ni se considerará que confiere a nadie ninguna licencia en virtud de los derechos de propiedad intelectual de Ecotact. Por lo tanto, los derechos para copiar, transmitir, reproducir, publicar, modificar y distribuir el mismo o cualquier parte del mismo no están permitidos sin el previo consentimiento escrito de Ecotact.',
    'Acceptable' => 'Uso Aceptado del Sitio Web',
    'Security' => 'Reglas de seguridad',
    'Visitors' => 'Los visitantes tienen prohibido violar o intentar violar la seguridad del sitio web, incluidos, entre otros,<br><br>1.	acceder a datos no destinados a dicho usuario o iniciar sesión en un servidor o cuenta a la que el usuario no está autorizado a acceder,<br>2.	intentar sondear, escanear o probar la vulnerabilidad de un sistema o red o violar las medidas de seguridad o autenticación sin la debida autorización,<br>3.	intentar interferir con el servicio a cualquier usuario, host o red, incluido, entre otros el envío de un virus o "caballo de Troya" al sitio web, la sobrecarga, la "inundación", el "bombardeo de correo" o el "bloqueo", o<br>4.	El envío de correo electrónico no solicitado, incluidas promociones y / o publicidad de productos o servicios. Las violaciones de la seguridad del sistema o de la red pueden resultar en responsabilidad civil o penal.<br>5.	usar cualquier dispositivo, software o rutina para interferir o intentar interferir con el correcto funcionamiento de este sitio web; o<br>6.	usar o intentar usar cualquier motor, software, herramienta, agente u otro dispositivo o mecanismo.<br><br>Ecotact tendrá derecho a investigar los sucesos que sospecha que involucran tales violaciones y tendrá derecho a involucrarse y a cooperar con las autoridades policiales para enjuiciar a los usuarios que estén involucrados en tales violaciones.',
    'General' => 'Reglas generales',
    'genVisitors' => 'Los visitantes no pueden utilizar el sitio web para transmitir, distribuir, almacenar o destruir material:<br><br>1. que podría constituir o fomentar una conducta que se consideraría un delito penal o violar cualquier ley o reglamento aplicable,,<br>2. de una manera que infrinja los derechos de autor, marca registrada, secreto comercial u otros derechos de propiedad intelectual de otros o que viole la privacidad o haga públicos los derechos personales de otros, o<br>3.  que sea calumnioso, difamatorio, pornográfico, profano, obsceno, amenazante, abusivo u incite al odio.',
    'Indemnity' => 'Indemnización / Limitación de Responsabilidad',
    'Your' => 'El uso de este sitio web es bajo su propio riesgo. Bajo ninguna circunstancia, Ecotact será responsable por pérdidas o daños directos o indirectos que surjan de o en conexión con su uso o incapacidad para usar este sitio web o su confianza en cualquier información proporcionada en este sitio web. Esta es una limitación integral de responsabilidad que se aplica a todas las pérdidas y daños de cualquier tipo, ya sean directos o indirectos, generales, especiales, incidentales, consecuenciales, ejemplares o de otro tipo, incluidos, entre otros, la pérdida de datos, ingresos o ganancias.',

];


