<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Home Page Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used during authentication for various
    | messages that we need to display to the user. You are free to modify
    | these language lines according to your application's requirements.
    |
    */

    'Terms' => 'Conditions d\'utilisation',
    'The' => 'Les termes “Nous” / “Nous” / “Notre”/ “Entreprise” / “Ecotact ”, se référer individuellement et collectivement à Aashirvad International et à d\'autres groupes ou filiales ou sociétés d\'investissement/coentreprises/affiliés autorisés et/ou ayants droit. Les termes “Visiteuse”/“Utilisatrice” référer aux utilisateurs. Ce site Web est destiné à être utilisé uniquement par des adultes âgés de plus de 18 ans. Si vous n\'êtes pas un adulte, vous ne devez pas vous inscrire ni nous soumettre d\'informations personnelles pendant que vous consultez notre site Web. Nous ne collectons pas sciemment des informations auprès de mineurs. En cas de défaillance du mineur, le parent ou le tuteur sera tenu de réparer tous dommages résultant d\'une telle utilisation abusive par le mineur. Ce site Web est détenu et exploité par Ecotact, dont le principal établissement est situé au 878, S P Mukherjee Marg, Delhi 110 006, Inde. Cette page énonce les termes et conditions selon lesquels vous (Visiteur) pouvez visiter ce site Web (« Site Web »). En accédant ou en utilisant simplement le site Web, vous reconnaissez, sans limitation ni réserve, être lié par les présentes conditions d\'utilisation et les politiques, que vous les ayez lues ou non. Si vous n\'acceptez pas les termes et conditions énoncés ici, nous vous demandons de quitter ce site. L\'entreprise, l\'une de ses divisions commerciales et/ou ses filiales, sociétés associées ou filiales de filiales ou autres sociétés d\'investissement (en Inde ou à l\'étranger) se réservent leurs droits respectifs de réviser ces conditions d\'utilisation à tout moment en mettant à jour cette publication. Nous nous réservons le droit de modifier ces termes et conditions de temps à autre sans aucune obligation de vous en informer et il est de votre responsabilité de les consulter aussi souvent que possible. Ces conditions d\'utilisation sont en vigueur jusqu\'à leur résiliation par vous ou par Ecotact. Vous pouvez résilier à tout moment, à condition de cesser toute utilisation ultérieure de ce site Web. Ecotact peut résilier les conditions d\'utilisation à tout moment et sans préavis, et en conséquence vous refuser l\'accès au site Web, sans aucune responsabilité envers le site Web.',
    'Intellectual' => 'Propriété intellectuelle',
    'All' => 'Tous les noms, logos et tous les noms de produits et de services, marques de conception et slogans associés sont des marques déposées et non déposées d\'Ecotact ou utilisées sous licence ou autorisation, par Ecotact et/ou ses entités associées. Tous les droits, y compris les droits d\'auteur, sur ce site Web sont la propriété de, sous licence ou autorisés à Ecotact. L\'accès à ce site Web ne confère et ne doit pas être considéré comme conférant à quiconque une licence au titre des droits de propriété intellectuelle d\'Ecotact. Par conséquent, les droits de copier, transmettre, reproduire, publier, modifier et distribuer le même ou une partie de celui-ci ne sont pas autorisés sans le consentement écrit préalable d\'Ecotact.',
    'Acceptable' => 'Utilisation acceptable du site Web',
    'Security' => 'Règles de sécurité',
    'Visitors' => 'Il est interdit aux visiteurs de violer ou de tenter de violer la sécurité du site Web, y compris, sans s\'y limiter,<br><br>1. accéder à des données non destinées à cet utilisateur ou se connecter à un serveur ou à un compte auquel l\'utilisateur n\'est pas autorisé à accéder,<br>2. tenter de sonder, scanner ou tester la vulnérabilité d\'un système ou d\'un réseau ou de violer des mesures de sécurité ou d\'authentification sans autorisation appropriée,<br>3. tenter d\'interférer avec le service à tout utilisateur, hôte ou réseau, y compris, sans s\'y limiter, par le biais de la soumission d\'un virus ou d\'un « cheval de Troie » sur le site Web, surcharge, « inondation », « mailbombing » ou « plantage », ou< br>4. l\'envoi de courrier électronique non sollicité, y compris les promotions et/ou la publicité de produits ou de services. Les violations de la sécurité du système ou du réseau peuvent entraîner une responsabilité civile ou pénale.<br>5. utiliser un appareil, un logiciel ou une routine pour interférer ou tenter d\'interférer avec le bon fonctionnement de ce site Web ; ou<br>6. utiliser ou tenter d\'utiliser tout moteur, logiciel, outil, agent ou autre appareil ou mécanisme<br><br>Ecotact aura le droit d\'enquêter sur les événements qu\'il soupçonne d\'impliquer de telles violations et aura le droit d\'impliquer et de coopérer avec , les autorités répressives dans la poursuite des utilisateurs impliqués dans de telles violations.',
    'General' => 'Règles générales',
    'genVisitors' => 'Les visiteurs ne peuvent pas utiliser le site Web pour transmettre, distribuer, stocker ou détruire du matériel :<br><br>1. qui pourraient constituer ou encourager une conduite qui serait considérée comme une infraction pénale ou violerait toute loi ou réglementation applicable,<br>2. d\'une manière qui enfreint le droit d\'auteur, la marque de commerce, le secret commercial ou d\'autres droits de propriété intellectuelle d\'autrui ou viole la vie privée ou la publicité d\'autres droits personnels d\'autrui, ou<br>3. qui est diffamatoire, diffamatoire, pornographique, profane, obscène, menaçant, abusif ou haineux.',
    'Indemnity' => 'Indemnité/Limitation de responsabilité',
    'Your' => 'Votre utilisation de ce site Web est à vos risques et périls. En aucun cas, Ecotact ne sera responsable des pertes ou dommages directs ou indirects résultant de ou en relation avec votre utilisation ou votre incapacité à utiliser ce site Web ou votre confiance dans les informations fournies sur ce site Web. Il s\'agit d\'une limitation complète de responsabilité qui s\'applique à toutes les pertes et dommages de quelque nature que ce soit, qu\'ils soient directs ou indirects, généraux, spéciaux, accessoires, consécutifs, exemplaires ou autres, y compris, sans limitation, la perte de données, de revenus ou de bénéfices.',

];


